### ISSUE TITLE
Fabric Support ?

### ISSUE THREAD

**Issue by KubilayKerim** [howljs/react-native-calendar-kit#1]
Hello currently  on fabric  project seems to giving errors due to @shopify/flash-list is not compatible with fabric right now https://github.com/Shopify/flash-list/issues/196
Just a heads up otherwise great work keep it up
<img width="395" alt="Screen Shot 2022-11-08 at 13 23 24" src="https://user-images.githubusercontent.com/18601583/200539899-02024de6-e576-40be-9e72-7a9cb521411f.png">

**Comment by howljs** [comment]
I think we need to wait for update from FlashList library 🥹
