### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by snettah** [howljs/react-native-calendar-kit#101]
Just wanted to say thank you. I believe this library has great potential. I haven't found anything equivalent for react-native; it's the only library that does the job.

**Comment by howljs** [comment]
@snettah 
Thank you for using it, and I hope you will continue to use it in the future. Version 2.0.0 has been completely rewritten and is in the final stages of completion. It helps improve performance and smoother animations.

https://github.com/howljs/react-native-calendar-kit/releases/tag/2.0.0-alpha.1
