### ISSUE TITLE
 Unable to Update Events When Dragged in React Native Timeline Calendar

### ISSUE THREAD

**Issue by sushitrash06** [howljs/react-native-calendar-kit#104]
I'm encountering an issue with my React Native application. I'm using the TimelineCalendar component from @howljs/calendar-kit to display events on a timeline. However, I'm unable to update events when they are dragged to a new position on the timeline. i dont need save button, i just need event always update when it dragged

I've set up the event handling functions, such as _onLongPressEvent and _onPressSubmit, but it seems that the events are not getting updated when dragged. I've also tried using useEffect to handle the event changes, but it didn't work either.

Could you please review my code and provide insights on why the events are not getting updated when dragged?
`import {
  EventItem,
  PackedEvent,
  RangeTime,
  TimelineCalendar,
} from '@howljs/calendar-kit';
import React, {useEffect, useState} from 'react';
import {
  SafeAreaView,
  StyleSheet,
  View,
  TouchableOpacity,
  Text,
} from 'react-native';
import {ScrollView} from 'ui/index';

const Calendar = () => {
  const [events, setEvents] = useState<EventItem[]>([]);
  const [selectedEvent, setSelectedEvent] = useState<PackedEvent>();

  const _onPressSubmit = () => {
    setEvents((prevEvents) =>
      prevEvents.map((ev) => {
        if (ev.id === selectedEvent?.id) {
          return {...ev, ...selectedEvent};
        }
        return ev;
      }),
    );
    setSelectedEvent(undefined);
  };

  const _onLongPressEvent = (event: PackedEvent) => {
    setSelectedEvent(event);
  };

  const _onDragCreateEnd = (event: RangeTime) => {
    const randomId = Math.random().toString(36).slice(2, 10);
    const newEvent = {
      id: randomId,
      title: randomId,
      start: event.start,
      end: event.end,
      color: '#A3C7D6',
    };
    setEvents((prev) => [...prev, newEvent]);
  };

  const _onEventChange = (changedEvent: EventItem) => {
    setEvents((prevEvents) =>
      prevEvents.map((ev) => {
        if (ev.id === selectedEvent?.id) {
          return {...ev, ...selectedEvent};
        }
        return ev;
      }),
    );
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView horizontal>
        <TimelineCalendar
          editEventGestureEnabled
          viewMode="week"
          events={events}
          initialDate={'2117-06-07'}
          maxDate={'2117-06-13'}
          minDate={'2117-06-07'}
          onLongPressEvent={_onLongPressEvent}
          selectedEvent={selectedEvent}
          onEndDragSelectedEvent={_onEventChange}
          allowDragToCreate
          onDragCreateEnd={_onDragCreateEnd}
          dragStep={20}
          firstDay={1}
          hourFormat="HH"
          hourWidth={32}
          initialTimeIntervalHeight={60}
          minTimeIntervalHeight={29}
          maxTimeIntervalHeight={110}
          theme={{
            dragHourContainer: {
              backgroundColor: '#FFF',
              borderColor: '#001253',
            },
            dragHourText: {color: '#001253'},
            editIndicatorColor: '#FFF',
            backgroundColor: '#191919',
            hourText: {
              color: '#FFF',
            },
            cellBorderColor: '#383838',
            dayNumber: {
              display: 'none',
              backgroundColor: '#191919',
            },
            sundayNumber: {
              display: 'none',
            },
            saturdayNumber: {
              display: 'none',
            },
            dayNumberContainer: {
              display: 'none',
            },
            saturdayNumberContainer: {
              display: 'none',
            },
            sundayNumberContainer: {
              display: 'none',
            },
            dayName: {
              marginBottom: -50,
              color: '#FFF',
            },
            saturdayName: {
              marginBottom: -50,
              color: '#FFF',
            },
            sundayName: {
              marginBottom: -50,
              color: '#FFF',
            },
          }}
          EditIndicatorComponent={
            <View style={{backgroundColor: 'red', width: '100%', height: 16}} />
          }
        />
      </ScrollView>
    </SafeAreaView>
  );
};

export default Calendar;

const styles = StyleSheet.create({
  container: {flex: 1, marginLeft: -20},
});`

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the example code if you want to use the library early.
