### ISSUE TITLE
[FEATURE] Add initial hour props

### ISSUE THREAD

**Issue by MihaiFloca** [howljs/react-native-calendar-kit#110]
Add an initial hour props to determine which hour the calendar should start on initial load

**Comment by howljs** [comment]
Updated in v2.0.2, you can use `goToDate` method in `onLoad` callback to scroll to the date and time

<img width="573" alt="Image from GitHub" src="https://github.com/user-attachments/assets/39a97966-affe-4926-bda2-b0e916af98ea">
