### ISSUE TITLE
[FEATURE REQUEST] - Show the exact date of events in calendar without converting to local timezone.

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#114]
Can we add a feature where we can show whatever date we passed in event object exactly mapped to the calendar. Right now, even if we don't specify a timezone, it converts to the local timezone. This could be a nice feature update as most react calendars support this kind of features.

**Comment by howljs** [comment]
please give me an example

**Comment by SwikarBhattarai** [comment]
Suppose, I passed an event object with date: 2024-11-03 4: 00 PM and want to show same exact time on calendar without converting to user's current timezone. This is not possible right now.  One user in UK with see different time and one user in USA will see different time right now. But i want every user to see the same time.

**Comment by howljs** [comment]
Timezone issues are really quite challenging. I’ll take some time to review this feature carefully

**Comment by howljs** [comment]
@SwikarBhattarai I just realized that to make an event appear at the same time everywhere, you just need to remove the timezone.

Example: Instead of `2024-10-13T05:00:00.00Z` you can use `2024-10-13T05:00:00.00`

https://github.com/user-attachments/assets/29e215d8-ad25-4798-b553-6dd951ff355d

**Comment by SwikarBhattarai** [comment]
@howljs The problem still exists. Suppose i set timezone to UK and the current time indicator goes to UK time but i want to keep the events dateTime to not change according to timezone its still not possible. Can you add one option to disableTimezone for Events only ? The current time should change according to the timeZone props.

**Comment by SwikarBhattarai** [comment]
nvm, i customized the library by adding nowIndicatorTimezone props.

**Comment by howljs** [comment]
> @howljs The problem still exists. Suppose i set timezone to UK and the current time indicator goes to UK time but i want to keep the events dateTime to not change according to timezone its still not possible. Can you add one option to disableTimezone for Events only ? The current time should change according to the timeZone props.

If possible, let me know which library has this feature or how you’re currently handling it so I can better understand what you’re aiming for. As I mentioned in my previous video response, if you want to maintain the timezone, we can either remove the timezone or update the event’s timezone while keeping the time unchanged.

**Comment by luisscruza** [comment]
I'm having this exact issue. I don't want to enforce timezone conversion for events, but want to keep the now indicator in the selected timezone... any workaround?
