### ISSUE TITLE
CalendarContainer does not  pass the onLongPressBackground prop to ActionsProvider

### ISSUE THREAD

**Issue by YaoHuiJi** [howljs/react-native-calendar-kit#115]
Hi, thank you for this great lib.

As the source code shows below,  the `onLongPressBackground` prop is not passed to `ActionsProvider`:

https://github.com/howljs/react-native-calendar-kit/blob/eb8f73cc0de5d81726de7b315425d71fd52b7893/packages/react-native-calendar-kit/src/CalendarContainer.tsx#L706-L721

**Comment by howljs** [comment]
wow. I missed it :'(

**Comment by howljs** [comment]
Fixed in v2.0.3
