### ISSUE TITLE
If the `timeInterval` prop of `CalendarContainer` is not set to the default value(60), `onPressBackground` will return an incorrect datetime.

### ISSUE THREAD

**Issue by YaoHuiJi** [howljs/react-native-calendar-kit#116]
Hi, I changed the `timeInterval` prop of `CalendarContainer` to a custom value, such as 15 or 30. When I tapped any position on the timeline, the `onPressBackground` event fired, but it returned the wrong datetime value. Tapping near the 0 o'clock position on the timeline returns a relatively accurate time. However, the farther the tap is from 0 o'clock, the greater the time deviation.

**Comment by howljs** [comment]
> Hi, I changed the `timeInterval` prop of `CalendarContainer` to a custom value, such as 15 or 30. When I tapped any position on the timeline, the `onPressBackground` event fired, but it returned the wrong datetime value. Tapping near the 0 o'clock position on the timeline returns a relatively accurate time. However, the farther the tap is from 0 o'clock, the greater the time deviation.

I forgot to test the case of changing the timeInterval. I’ll check and fix it soon.

**Comment by howljs** [comment]
Fixed in v2.0.3
