### ISSUE TITLE
Custom LeftAreaComponent need some inner states of CalendarHeader to implement its own ExpandButton

### ISSUE THREAD

**Issue by YaoHuiJi** [howljs/react-native-calendar-kit#117]
When customizing `LeftAreaComponent`, some internal states of `CalendarHeader` are needed to implement certain functionalities. For example, in the current code, once a custom `LeftAreaComponent` is provided, the `ExpandButton` will not be displayed, making it impossible to expand or collapse the `CalendarHeader`, so we need some inner state of `CalendarHeader`  like `isExpanded`,`isShowExpandButton`,'renderExpandIcon' etc. to write our own ExpandButton.

So, I think it might be more flexible if LeftAreaComponent is a function that can accept parameters?

like this:
```
<View style={[styles.leftArea, { width: hourWidth }]}>
          {LeftAreaComponent({ visibleDateUnixAnim, useAllDayEvent, isExpanded,isShowExpandButton, renderExpandIcon })}
</View>
```

instead of:
```
<View style={[styles.leftArea, { width: hourWidth }]}>
          {LeftAreaComponent}
</View>
```

**Comment by howljs** [comment]
My intention is that instead of passing just a few params, you can use a custom hook to handle everything. In fact, I’m exporting quite a bit so that everyone can rewrite the entire Header or Body if needed

https://github.com/user-attachments/assets/7f5a86e7-04e3-423d-a4f5-71b0481d177c

**Comment by YaoHuiJi** [comment]
Wow, that's really cool! Sorry, I didn’t carefully read the source code. I didn’t realize there was such an easy way to access those states. Thank you for your reply! I'll close this issue.
