### ISSUE TITLE
Double and missing days

### ISSUE THREAD

**Issue by yrichtermeier** [howljs/react-native-calendar-kit#118]
### Hi, thanks for this libraray. 
I have a problem displaying the calendar. Starting on monday and ending on sunday every week, I get October 27th 2024 twice and there are no events displayed after this date. The whole calendar is then postponed by one day. Sunday is also the first day of the week after it until March 30th 2025, because March 30th 2025 is completely missing. 
For example, October 26th 2025 is shown twice again. 

**Example - October 27th 2024:**
![October1](https://github.com/user-attachments/assets/fd443490-5632-45c3-9cb1-c2b49871610a)
![October2](https://github.com/user-attachments/assets/e1b59660-c792-43be-98fc-b7d5fcc41e4b)

**Example - March 30th 2025:**
![March1](https://github.com/user-attachments/assets/d4db8de8-6ebe-4359-b8a7-e4d84b3a9032)
![March2](https://github.com/user-attachments/assets/54d14c85-49cc-47e1-b30a-12088f0ae284)

Does anyone else have this problem?

_"@howljs/calendar-kit": "2.0.2",
"@shopify/flash-list": "^1.6.3",
"expo": "~51.0.35",
"react": "18.2.0",
"react-native": "0.74.5",
"react-native-reanimated": "~3.10.1",_

**Comment by howljs** [comment]
It seems that this issue is related to the time zone. Please give me the time zone on your device

**Comment by yrichtermeier** [comment]
> It seems that this issue is related to the time zone. Please give me the time zone on your device

UTC+02:00 (MESZ) right now and UTC+01:00 (MEZ) after October 27th 2024
In March the problem also occurs when time changes from UTC+01:00 (MEZ) to UTC+02:00 (MESZ)

**Comment by Raphitpt** [comment]
Hi, i have the same problem, i think is summer date

**Comment by howljs** [comment]
Fixed in v2.0.3
