### ISSUE TITLE
scrollToNow don't work in with 1 day

### ISSUE THREAD

**Issue by Raphitpt** [howljs/react-native-calendar-kit#119]
First of all, congratulations for this upgrade, it is very successful and very fluid. 

I managed to migrate without too many problems and this new update brings corrections compared to version 1. I noticed that when we have 1 day, the scroll to now is not done on the right day or is not done at all. Likewise with the goToDate function which is done 1 day before. 

Thank you for your work

**Comment by howljs** [comment]
These issues are likely related to the timezone. Please provide me with the timezone on your device, and I will proceed to check and fix the error in the next version

**Comment by howljs** [comment]
Ah, I saw your comment on the previous issue. Just as I predicted, it’s a timezone-related bug. I’ll fix it soon.

**Comment by howljs** [comment]
Fixed in v2.0.3

**Comment by Raphitpt** [comment]
Nice work, it's work perfectly. I propose a feature that was good on v1, it was the possibility of removing the half-time lines and in week view, above the week number, display the month with 3 letters. Otherwise very good job

**Comment by howljs** [comment]
There will definitely be an option to customize the half line in the upcoming version. I had planned to update it soon but unfortunately, I forgot.

**Comment by howljs** [comment]
To show the month, you can watch this video, you can customize it through custom hooks

https://github.com/howljs/react-native-calendar-kit/issues/117#issuecomment-2395124485
