### ISSUE TITLE
Is it possible to implement a custom 'now' button inside the 'day header'?

### ISSUE THREAD

**Issue by fkranenburg** [howljs/react-native-calendar-kit#12]
We are actively integration this component inside our app, but we need to have a simple button to quickly go to the current date. I can't use the header of the screen itself but we have room in the day header because we always show one day at a time. Is there any was to implement a custom component (right or left)?

**Comment by j2teamlbh** [comment]
You can write a custom component and use ref: https://howljs.github.io/react-native-calendar-kit/docs/guides/methods

![Screenshot 2022-12-05 at 19 20 15](https://user-images.githubusercontent.com/45052513/205635873-a79eacf1-9866-499d-892a-0f407b9911a8.png)
