### ISSUE TITLE
Is the dragToCreate behavior the same as in version 1.xx?

### ISSUE THREAD

**Issue by snettah** [howljs/react-native-calendar-kit#129]
In version 2.xx, can't we have the same behavior as in version 1.xx?

I only need the start time and to move the new event across days.

What I see in the 2xx it's not possible to have the same thing.

https://github.com/user-attachments/assets/f0473f0b-2399-4968-b3d7-bb7f681fb47a

**Comment by howljs** [comment]
I will add it in the next version

**Comment by howljs** [comment]
Added in v2.2.0, please check it

1. Add `dragToCreateMode="date-time"` to CalendarContainer

![Screenshot 2024-11-04 at 14 08 40](https://github.com/user-attachments/assets/2ebbcb54-cd0f-4c0e-8a28-0e369942d6de)

3. Custom draggingEvent:

![Screenshot 2024-11-04 at 14 08 14](https://github.com/user-attachments/assets/4ca435e5-7ec0-4c95-9e8e-73afc71cc915)

Example: https://github.com/howljs/react-native-calendar-kit/blob/427a50e32e364ff61c594f06f831896b4a76c836/apps/example/app/(drawer)/index.tsx#L696

**Comment by snettah** [comment]
Thank you very much !
