### ISSUE TITLE
Clicking the slot doesn't trigger anything

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#133]
I want to create a new event while Clicking the slot but i couldn't find any props for it now.

**Comment by howljs** [comment]
I think it will be `onPressBackground`

**Comment by SwikarBhattarai** [comment]
https://github.com/user-attachments/assets/bce050a3-7940-41 b33d-44f9b46d9e3b

@ho

https://github.com/user-attachments/assets/34aeb879-8b9d-4536-bb9c-a48af77fce5a

while doing this i want to trigger something without dragging. is it possible ?

**Comment by howljs** [comment]
You can set selectedEvent when press background

**Comment by SwikarBhattarai** [comment]
Ok problem solved for now . Thanks
