### ISSUE TITLE
[QUESTION] How to show customUnavailableHourItem in 2.0 ? Doing like 1.0 doesn't seems to work.

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#135]

**Comment by howljs** [comment]
you can use `renderCustomUnavailableHour` in CalendarBody. I forgot to add it to the document

**Comment by SwikarBhattarai** [comment]
const _renderCustomUnavailableItem = () => useMemo(
        (props) => <BreakItem {...props} />,
        []
    );
    
    import React from 'react';
import Animated, { useAnimatedProps } from 'react-native-reanimated';
import Svg, { Defs, Line, Pattern, Rect } from 'react-native-svg';

const AnimatedRect = Animated.createAnimatedComponent(Rect);

const BreakItem = (props) => {
  const patternSize = 5;

  const rectProps = useAnimatedProps(() => ({
    height: props.height
  }));

  return (
    <Svg>
      <Defs>
        <Pattern
          id="stripe-pattern"
          patternUnits="userSpaceOnUse"
          width={patternSize}
          height={patternSize}
          patternTransform="rotate(-45)"
        >
          <Line
            x1={0}
            y={0}
            x2={0}
            y2={patternSize + 5}
            stroke="#e8e8e8"
            strokeWidth={1.5}
            strokeLinecap="butt"
          />
        </Pattern>
      </Defs>
      <AnimatedRect
        x="0"
        y="0"
        width="100%"
        fill="url(#stripe-pattern)"
        animatedProps={rectProps}
      />
    </Svg>
  );
};

export default BreakItem;

**Comment by SwikarBhattarai** [comment]
@howljs pattern doesn't seem to work now. I tried like above but its rendering only the default color.

**Comment by howljs** [comment]
> @howljs pattern doesn't seem to work now. I tried like above but its rendering only the default color.

Full code:

```CustomUnavailableHour.tsx
import { UnavailableHourProps } from '@howljs/calendar-kit';
import React, { FC } from 'react';
import Animated, {
  SharedValue,
  useAnimatedProps,
} from 'react-native-reanimated';
import { Defs, Line, Pattern, Rect, Svg } from 'react-native-svg';

const AnimatedRect = Animated.createAnimatedComponent(Rect);

const CustomUnavailableHour: FC<
  UnavailableHourProps & {
    width: SharedValue<number>;
    height: SharedValue<number>;
  }
> = (props) => {
  const patternSize = 5;

  const rectProps = useAnimatedProps(() => ({
    height: props.height.value,
  }));

  return (
    <Svg>
      <Defs>
        <Pattern
          id="stripe-pattern"
          patternUnits="userSpaceOnUse"
          width={patternSize}
          height={patternSize}
          patternTransform="rotate(-45)">
          <Line
            x1={0}
            y={0}
            x2={0}
            y2={patternSize + 5}
            stroke="red"
            strokeWidth={1.5}
            strokeLinecap="butt"
          />
        </Pattern>
      </Defs>
      <AnimatedRect
        x="0"
        y="0"
        width="100%"
        fill="url(#stripe-pattern)"
        animatedProps={rectProps}
      />
    </Svg>
  );
};

export default CustomUnavailableHour;

```Calendar.tsx
 const renderCustomUnavailableHour = useCallback(
    (
      props: UnavailableHourProps & {
        width: SharedValue<number>;
        height: SharedValue<number>;
      }
    ) => {
      return <CustomUnavailableHour {...props} />;
    },
    []
  );

<CalendarBody
          renderCustomUnavailableHour={_renderCustomUnavailableHour}
        />
```

Result:

![simulator_screenshot_4DDE0EF8-1490-4FA9-AE75-441C8AE32C44](https://github.com/user-attachments/assets/1459717e-1dfc-4196-93a0-6735eef89755)

**Comment by SwikarBhattarai** [comment]
Thanks . Works perfectly!

**Comment by SwikarBhattarai** [comment]
https://github.com/user-attachments/assets/fcf8e673-639b-417e-8b60-353c2c0a8c89

Once check this as well it kinda looks like a bug.
When dragged only it triggers but doesn't trigger when not dragged

**Comment by howljs** [comment]
I’ve received the notification about this bug, and I will fix it in the next version.

https://github.com/howljs/react-native-calendar-kit/issues/130

**Comment by SwikarBhattarai** [comment]
ok Thanks closing this.

**Comment by SwikarBhattarai** [comment]
<img width="451" alt="Screenshot 2024-10-16 at 5 31 08 PM" src="https://github.com/user-attachments/assets/5b3d3cc5-3e00-4bed-bb5f-4449374bd096">
once check this as well when going from weekly to 3 days view.
