### ISSUE TITLE
【BUG】创建两个事件，第一个终点是24:00，第二个从0点开始，会出现这样的问题

### ISSUE THREAD

**Issue by JiuMengDz** [howljs/react-native-calendar-kit#139]
![image](https://github.com/user-attachments/assets/7822c0ca-abe5-4312-b2af-12d95bab3aa0)
![image](https://github.com/user-attachments/assets/a958eb51-2ea9-4db3-8411-307651c5787c)
而且这两个均无法被选中。
![image](https://github.com/user-attachments/assets/86ab9779-dc81-43b8-bff9-d0b213968e73)
![image](https://github.com/user-attachments/assets/a7076c43-84cc-4cc5-8f88-094bb1ee2e4d)

**Comment by howljs** [comment]
Please help me check in the new version

**Comment by JiuMengDz** [comment]
问题依然存在  这是我两个事件的信息日志
![image](https://github.com/user-attachments/assets/61e3ea54-a3db-4637-b79d-fa44a73b3101)

**Comment by JiuMengDz** [comment]
另外我发现第二天的0点之前的部分会额外渲染前一天的，但是我取消选中它就不渲染了
![image](https://github.com/user-attachments/assets/f8492b32-898c-498f-8cc9-a6f6cc4a1e75)

**Comment by JiuMengDz** [comment]
> Please help me check in the new version

事件目前可以被选中了
