### ISSUE TITLE
Is it possible to view calendar for multiple resources

### ISSUE THREAD

**Issue by vtherli** [howljs/react-native-calendar-kit#14]
Please find the example below:

![image](https://user-images.githubusercontent.com/1889295/205922389-eef963d1-968e-4887-9ae9-110e3251a574.png)

**Comment by howljs** [comment]
In the project I am working on there is a similar feature but I have not yet developed it for this library. 😅

![image](https://user-images.githubusercontent.com/33460888/205950314-85d71d0b-73d6-4ca9-b327-a6f02365b354.png)

**Comment by howljs** [comment]
sr @vtherli, I don't know any library have this feature

**Comment by vtherli** [comment]
@howljs Can you share your linkedin link so we can connect. Thanks.
