### ISSUE TITLE
Calendar Provider

### ISSUE THREAD

**Issue by emrekazaz-hub** [howljs/react-native-calendar-kit#144]
Hi, i wanted to use custom hooks of calendar but can not find provider export. I need to wrap my components with calendars provider than use them with hook, or is there another way that i don't know. Here is the example part of my code.

import {
  CalendarBody,
  CalendarContainer,
  CalendarHeader,
  DayItem,
  EventItem,
  LocaleConfigsProps,
  RenderHourProps,
  useCalendar,
// no imports for  CalendarContext or CalendarProvider 
} from "@howljs/calendar-kit";

.........

const SchedulerScreen: React.FC = () => {
  const calendarContext = useCalendar();
  const visibleUnix = calendarContext.visibleDateUnix;

  return (
    <CalendarContainer>
      <CalendarHeader />
      <CalendarBody />
    </CalendarContainer>
  );
}

Error: useCalendar must be used within a CalendarProvider

**Comment by howljs** [comment]
I am in the process of breaking down the components to make them easier to customize, but for now, I think you can create child components within the CalendarContainer.

<img width="620" alt="Screenshot 2024-10-23 at 14 34 00" src="https://github.com/user-attachments/assets/6bb29ce1-617e-4180-ae42-b82e9b07c20d">

**Comment by emrekazaz-hub** [comment]
Yes, I tried it and it works as you said. I can use it like this for now. Thank you for the quick response and Good luck !!

**Comment by howljs** [comment]
> Yes, I tried it and it works as you said. I can use it like this for now. Thank you for the quick response and Good luck !!

Be sure to avoid using useCalendar inside components within the list, as it will cause unnecessary rerenders. If you’re customizing items inside CalendarHeader, use useHeader. And if you’re customizing items in CalendarBody, use useBody. useCalendar should only be used outside of CalendarBody and CalendarHeader.
