### ISSUE TITLE
Optional line between hours

### ISSUE THREAD

**Issue by CarnageXD** [howljs/react-native-calendar-kit#145]
Is there a way to get rid of the line between hours by using props?

<img width="169" alt="image" src="https://github.com/user-attachments/assets/add6ba7e-b6d5-483a-a6e7-ad6bba6a9584">

I can't find the logic for this in the documentation, but I did a little research in the source code and found that if I remove this code from the `TimelineBoard/index.tsx' component, it looks as intended:
```
   rows.push(
        <HorizontalLine
          key={`${i}.5`}
          borderColor={colors.border}
          index={i + 0.5}
          height={timeIntervalHeight}
        />
      );
```

<img width="150" alt="image" src="https://github.com/user-attachments/assets/a9a1856d-b6db-4b78-a450-3a12a4d0ff18">

If it doesn't affect the internal logic and is just a visual thing, can I request a feature to support this?

**Comment by howljs** [comment]
I forgot to update it again 😅 I will update more properties to customize it in the next version

**Comment by CarnageXD** [comment]
@howljs sounds great! thank you!

**Comment by howljs** [comment]
@CarnageXD Leave it open so I can remember that I need to update. I will close it when it’s done

**Comment by howljs** [comment]
Added in v2.2.0. Please check it

Example: https://github.com/howljs/react-native-calendar-kit/blob/427a50e32e364ff61c594f06f831896b4a76c836/apps/example/app/(drawer)/index.tsx#L512

![Screenshot 2024-11-04 at 14 10 49](https://github.com/user-attachments/assets/91c3dfec-5823-45e0-a48d-a10e4edc472c)
