### ISSUE TITLE
Drag to Reschedule - Daylight Savings Bug

### ISSUE THREAD

**Issue by darren4flow** [howljs/react-native-calendar-kit#147]
If I drag an event to reschedule it on November 3rd, then it's rescheduled an hour earlier than where I dropped it.

November 3rd is the day we turn our clocks back an hour at 2am because of daylight savings. 

I've attached a video demonstration. 

https://github.com/user-attachments/assets/7680d192-99d4-464f-98fc-ab946ee0fc3b

**Comment by darren4flow** [comment]
I tried it again today and rescheduling events that are scheduled today are also being scheduled an hour earlier than where I dropped it.

Could this be because of daylight savings?

**Comment by howljs** [comment]
Fixed in v2.2.0, please check it

**Comment by darren4flow** [comment]
Hi, thank you for addressing this!

How can I properly upgrade to version 2.2.0 from 2.1.0?

If I just run:

`yarn upgrade @howljs/calendar-kit@latest`

Then I'll get this error from useDragEventGesture.tsx when running the app:

` ERROR  TypeError: _reactNativeGestureHandler.Gesture.Pan().blocksExternalGesture is not a function (it is undefined)`

And if I also run this to upgrade these two packages to match the versions in your example app:

`yarn add react-native-gesture-handler@2.16.1 react-native-reanimated@2.16.1`

Then the drag to edit feature isn't working. I'll long press on an event to drag it but the event doesn't move. 

The same problem occurs when I install the latest versions of these packages, plus an additional warning appears as well.

Please tell me what I should do to get version 2.2.0 working.
