### ISSUE TITLE
Hours on drag doesnt work correctly

### ISSUE THREAD

**Issue by KacperGora** [howljs/react-native-calendar-kit#18]
When I've set the start and end hoour and then started dragging for creating new event the hour highlighted on left side by blue color, doesnt show proper time, still using old start-end 

https://user-images.githubusercontent.com/98807756/206170666-fe76bca6-def6-4a84-9b6f-5b4937cc7da6.MP4

range from 0 to 24

**Comment by howljs** [comment]
I fixed on [v1.8.3](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.8.3), thanks ♥
