### ISSUE TITLE
When using timezone, the events are not aligned with the time. After, i remove timezone, then they are aligned.

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#19]
<img width="334" alt="Screen Shot 2022-12-09 at 2 15 54 PM" src="https://user-images.githubusercontent.com/36293831/206659162-6039637e-7e73-4a0e-8ce9-b082246474b9.png">

**Comment by howljs** [comment]
Can you share me your data?

**Comment by howljs** [comment]
I tested in my example, it's working normally

**Comment by SwikarBhattarai** [comment]
@howljs [{"color": "#95e3cb", "containerStyle": {"borderLeftColor": "#76b6a3", "borderLeftWidth": 5, "borderRadius": 6, "borderStyle": "solid"}, "end": 2022-12-07T15:30:00.000Z, "id": "0a394f7d-e08c-4ecf-8948-9dd71a54e995", "start": 2022-12-07T15:00:00.000Z, "title": "Sample Service with Hello Kumar"}, {"color": "#95e3cb", "containerStyle": {"borderLeftColor": "#76b6a3", "borderLeftWidth": 5, "borderRadius": 6, "borderStyle": "solid"}, "end": 2022-12-07T16:15:00.000Z, "id": "cb5a38ea-8034-4ec2-a0ab-079c0bf4d959", "start": 2022-12-07T15:45:00.000Z, "title": "Sample Service with Hello Kumar"}, {"color": "#95e3cb", "containerStyle": {"borderLeftColor": "#76b6a3", "borderLeftWidth": 5, "borderRadius": 6, "borderStyle": "solid"}, "end": 2022-12-08T15:15:00.000Z, "id": "e809c559-92ca-4e5a-82c5-9f296ab4663e", "start": 2022-12-08T14:45:00.000Z, "title": "Sample Service with Hello Kumar"}, {"color": "#95e3cb", "containerStyle": {"borderLeftColor": "#76b6a3", "borderLeftWidth": 5, "borderRadius": 6, "borderStyle": "solid"}, "end": 2022-12-09T14:15:00.000Z, "id": "92b62aeb-9935-4708-8f2b-415d0527e8dd", "start": 2022-12-09T13:45:00.000Z, "title": "Sample Service with Hello Kumar"}]. with timezone set in Asia/Kabul.

**Comment by SwikarBhattarai** [comment]
@howljs can you share your example data too, let me test with that.

**Comment by howljs** [comment]
[{"color": "hsl(280.46288950388947,90.83731554641659%,92.06792192480457%)", "containerStyle": {"borderColor": "#7C54CC", "borderWidth": 1}, "end": "2022-12-07T03:00:00.000Z", "id": "madkfl09", "start": "2022-12-07T02:00:00.000Z", "title": "madkfl09"}, {"color": "hsl(98.27229491845677,56.28418942403897%,86.00876348713345%)", "containerStyle": {"borderColor": "#D1694D", "borderWidth": 1}, "end": "2022-12-08T04:00:00.000Z", "id": "upownu5x", "start": "2022-12-08T03:00:00.000Z", "title": "upownu5x"}]

Timezone: "Asia/Ho_Chi_Minh"
ID: madkfl09 -> 2022-12-07 09:00
ID: upownu5x -> 2022-12-08 10:00

**Comment by SwikarBhattarai** [comment]
@howljs i am currently in nepal. When i set Asia/Kathmandu then its work perfect but when i set other timezones like Asia/Kabul then the above issue occurs.

**Comment by SwikarBhattarai** [comment]
<img width="310" alt="Screen Shot 2022-12-09 at 3 31 29 PM" src="https://user-images.githubusercontent.com/36293831/206673517-7d1eaf6c-5ba7-4b5b-b0d4-dbcc2adc23f2.png">
@howljs check this.

**Comment by howljs** [comment]
That's different time zone.

Asia/Kathmandu
![Screenshot 2022-12-09 at 16 46 55](https://user-images.githubusercontent.com/33460888/206673625-c84908e0-5bf0-4f80-bb97-82c8503e1f9b.png)

Asia/Kabul
![Screenshot 2022-12-09 at 16 47 35](https://user-images.githubusercontent.com/33460888/206673799-507fe05e-3b0e-4ec2-a514-4b1d3c5a2d98.png)

**Comment by SwikarBhattarai** [comment]
How to solve this, can you explain? i didn't understand.

**Comment by howljs** [comment]
I think I saw the problem. now I will check it out, I will reply to you soon

**Comment by SwikarBhattarai** [comment]
@howljs Thanks. I hope you will find the solution soon. It is a quite urgent :-D

**Comment by howljs** [comment]
I have some mistakes. I think it works normally.

**Time Zone Converter**
![Screenshot 2022-12-09 at 17 15 31](https://user-images.githubusercontent.com/33460888/206679180-86376490-e65e-40fa-803a-f4ea91a37988.png)

**Asia/Ho_Chi_Minh**
![Screenshot 2022-12-09 at 17 17 41](https://user-images.githubusercontent.com/33460888/206679569-333ce9c0-b225-4244-a65c-97081f15b32e.png)

**Asia/Kathmandu**
![Screenshot 2022-12-09 at 17 18 11](https://user-images.githubusercontent.com/33460888/206679660-d62f2e52-a260-474f-9a0c-07e1dccf201a.png)

**Asia/Kabul**
![Screenshot 2022-12-09 at 17 17 18](https://user-images.githubusercontent.com/33460888/206679489-2e7f2dfa-53eb-4ef4-b22f-b8dbef5f1cb1.png)

**Comment by SwikarBhattarai** [comment]
@howljs the same library or need to push some changes?

**Comment by howljs** [comment]
@SwikarBhattarai  The same

**Comment by howljs** [comment]
This is my custom event content
![Screenshot 2022-12-09 at 17 23 35](https://user-images.githubusercontent.com/33460888/206680737-04e1e6c2-a7db-4561-b479-19307f1ab944.png)

**Comment by SwikarBhattarai** [comment]
@howljs Thanks. You can close this :-)
