### ISSUE TITLE
changing from week to day viewmode with onpress takes me to wrong day

### ISSUE THREAD

**Issue by ChristopherL-creator** [howljs/react-native-calendar-kit#24]
Hello, as the title says, i assigned an onpress to a FAB, to change the calendar view from "week" to "day". 

However, when i press the fab to access the day viewmode, it takes me to the previous day. 

apparently this happens only when changing to viewmode="day" with the onpress, initializining the calendar with viewmode="day" or "week", displays the correct dates. 

here's the code for reference: 
` 
const actions = [
    {
      text: "Oggi",
      icon: require("../../../assets/Week-icon.png"),
      name: "day",
      position: 1
    },
    {
      text: "Settimana",
      icon: require("../../../assets/Today-icon.png"),
      name: "week",
      position: 2
    },
  ];

const Calendar = () => {  
    
    const [isView, setIsView] = useState<CalendarViewMode>('week'); 
    console.log('isView start', isView);
    
    
    const onPressButton = (name: String) => {
        if(name === "week") setIsView("week");
        if(name === "day") setIsView("day"); 

        console.log('isView onPress', isView);
    }

    return ( 
        <> 
            <TimelineCalendar 
            locale='it'
            allowPinchToZoom
            initialTimeIntervalHeight={60}
            minTimeIntervalHeight={29}
            maxTimeIntervalHeight={110}
            halfLineContainerStyle={calendareStyles.container}
            viewMode={isView} /> 
            
            <FloatingAction
            actions={actions}
            color={"blue"}
            onPressItem={name => {
              onPressButton(name);
            }}
            floatingIcon= {require("../../../assets/calendar-icon.png")}
            iconWidth={30}
            iconHeight={23} /> 
        </> 
    );
} 

export default Calendar;
`
Thank you =)

**Comment by ChristopherL-creator** [comment]
update: once in the wrong viewmode: 'day', pressing they viewmode: 'day' button again takes me to the correct date. i'm new to react and react native, but could this be about asynchronous logics?

**Comment by FernandoAlvesMachado** [comment]
Any News??
