### ISSUE TITLE
Background color of event (not content)

### ISSUE THREAD

**Issue by gunnartorfis** [howljs/react-native-calendar-kit#26]
I'm trying to change the background color of the event itself, and even stuff like the border radius. 
What I'd ideally want is to make the root event's background color to be transparent. The reason is that I need to render part of the event content with ~30% opacity, which isn't possible currently since the event has a fixed background of white. 

I want to end with a huge thank you for this amazing library. Fantastic work 👏

**Comment by howljs** [comment]
https://howljs.github.io/react-native-calendar-kit/docs/guides/events#color
you can set color and containerStyle of event
![Screenshot 2023-01-08 at 13 48 52](https://user-images.githubusercontent.com/33460888/211184100-4c1ab49f-0164-41ed-b80e-d8281c07d9f8.png)

**Comment by gunnartorfis** [comment]
Oh, thanks a lot! I totally looked passed the color prop after I saw containerStyle was available.
