### ISSUE TITLE
Hours not showing on physical device

### ISSUE THREAD

**Issue by jgoldm** [howljs/react-native-calendar-kit#32]
![react-native-calendar-kit](https://user-images.githubusercontent.com/67298376/213033942-5b52f4e1-4c1d-4c3c-a944-d7a0a023be8f.jpg)

Hello, I cannot get the hours to show on the left hours column. 

Edit: I tested on emulator and the hours are showing. Default font color on physical android devices is white, which is why the hours do not show because the background is also white.

Solved with: theme={{hourText: {color: 'black'}}}

Thank you

**Comment by BabakYaghoobi** [comment]
Same issue !

**Comment by howljs** [comment]
I updated default text color in [v1.12.0](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.12.0)
