### ISSUE TITLE
No indication to the user of the month or year

### ISSUE THREAD

**Issue by greenboots88** [howljs/react-native-calendar-kit#34]
In the video example and documentation is no indication of the month or the year.

Can this be added to the header instead of the word 'Calendar', i.e January 2022.

It would be a good use of space without compromising / reducing the diary.

**Comment by greenboots88** [comment]
Another option, is to put the month next to the date in the header, instead of 
20 in the blue circle, it could be 20/01.

DD/MM

**Comment by greenboots88** [comment]
@howljs Has anyone else mentioned how vital to the end user it is, being able to see the month?

**Comment by howljs** [comment]
In the example video, I only show the basic user interface, you can run the example project for details

Bare Project: https://github.com/howljs/react-native-calendar-kit/tree/main/example
Expo: https://github.com/howljs/expo-calendar-example

**Comment by howljs** [comment]
You can write a Custom Component to show date by [onChange](https://howljs.github.io/react-native-calendar-kit/docs/guides/other-props#onchange) prop
