### ISSUE TITLE
[REQ] option for setting initial time on start

### ISSUE THREAD

**Issue by krskrs** [howljs/react-native-calendar-kit#38]
Hi, 
I've seen that it's possible to navigate to a given time (in addition to date) through the goToDate() method, but would it be possible to pass a 'scrollToTime' value also on component boot? Maybe by adding support for passing time to the initialDate prop?

Or is it already possible with current API?

The rationale behind this request is to be able to position the view directly at the start time of the first event of interest, skipping, for example, the empty hours before such event, but without having to change the day start hour with the start prop.

Thank you,
fc

**Comment by howljs** [comment]
I think you can custom scroll position when component mounted
<img width="749" alt="Screenshot 2023-03-11 at 08 23 48" src="https://user-images.githubusercontent.com/33460888/224457154-ea7b2d22-18cc-4a23-bc69-7bc3b61e5e77.png">
