### ISSUE TITLE
Responsive issue 

### ISSUE THREAD

**Issue by umeshbaldania** [howljs/react-native-calendar-kit#39]
I have used TimelineCalendar in my app. 
i did not have full screen timeline calendar, due to we have some padding and stick drawer.

See attached have only 6 day fit to screen. 
![Screenshot 2023-02-14 at 6 47 35 PM](https://user-images.githubusercontent.com/88178068/218750103-f3b7f28a-cb6d-402a-8f18-e05a28355483.png)

**Comment by howljs** [comment]
I added calendarWidth in [v1.12.0](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.12.0)
