### ISSUE TITLE
issue with initialDate

### ISSUE THREAD

**Issue by giannischiout** [howljs/react-native-calendar-kit#40]
when the day changes initialDate doesnt update properly. This happens when i navigate to a new screen on onPressEvent. When i try to navigate back afterwards with a new date, the initialDate does not change

**Comment by OrestLue** [comment]
I faced the same problem
Add the same value to the key as in initialDate to make the calendar update
<TimelineCalendar
          key={initialDate}
          initialDate={initialDate}
          ...

**Comment by OrestLue** [comment]
> when the day changes initialDate doesnt update properly. This happens when i navigate to a new screen on onPressEvent. When i try to navigate back afterwards with a new date, the initialDate does not change

I faced the same problem
Add the same value to the key as in initialDate to make the calendar update
<TimelineCalendar
key={initialDate}
initialDate={initialDate}
...
