### ISSUE TITLE
[Questions] Get time slot on onPressBackground

### ISSUE THREAD

**Issue by gbettinazzi** [howljs/react-native-calendar-kit#42]
Hello! first of all let me tell you that this is the library every developer who has to deal with dates is looking for! 
I'd like to know if there's any way to retrieve the selected time slot when onPressBackground is fired because I only get the current date but not the time. 

thanks!

**Comment by howljs** [comment]
I added current time when onPressBackground in [v1.12.0](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.12.0)

**Comment by gbettinazzi** [comment]
@howljs yes I confirm it works! Thanks a lot!
