### ISSUE TITLE
Integrate Dynamic Timezone

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#45]
Instead of using constant timezones, can you integrate dynamic timezone. Currently there is issue in Now indicator in daylight saving for Australia/Sydney and others timezones.

**Comment by callaars** [comment]
If you use the code at PR #28 then it will resolve your issue :)

**Comment by howljs** [comment]
@SwikarBhattarai I have updated the new version, you can update it and try again
