### ISSUE TITLE
onPressBackground gives wrong Timeslot information on user press  react-native-calendar-kit

### ISSUE THREAD

**Issue by muhammadashfaq** [howljs/react-native-calendar-kit#47]
Hi. I am implementing the react-native-calendar-kit in one of my projects.    onPressBackground gives the wrong timeslot information when the user presses it.

Any workaround?

thanks

**Comment by Jack-Alfie** [comment]
Hi I am facing the same issue too for me it always return the time as 18:30.
I am using version "^1.11.1"

**Comment by Jack-Alfie** [comment]
Fixed in version 1.13.0 thanks

**Comment by howljs** [comment]
I pushed a commit about onPressBackground return wrong time when set timeZone. I think it will include in v1.13.1 🤧

**Comment by howljs** [comment]
Fixed in v1.13.1
