### ISSUE TITLE
Dragging not working in Android

### ISSUE THREAD

**Issue by Jack-Alfie** [howljs/react-native-calendar-kit#49]
Dragging is not working in android but it's working fine in iOS.  Kindly check the code and video attached 

<TimelineCalendar
    ref={calendarRef}
    viewMode={viewMode}
    events={events}
    initialDate={selectedWeekViewDate}
    unavailableHours={unavailableHours}
    isLoading={loading}
    onChange={_onChange}
    onPressOutBackground={() => {
      setIsModelVisible(false)
      setIsDatePickerVisible(false)
    }}
    onLongPressEvent={_onLongPressEvent}
    onPressEvent={onPressEvent}
    onPressBackground={onGridClick}
    selectedEvent={selectedEvent}
    onEndDragSelectedEvent={setSelectedEvent}
    dragStep={20}
    theme={{
      dragHourColor: '#001253',
      dragHourBorderColor: '#001253',
      dragHourBackgroundColor: '#FFF',
      editIndicatorColor: '#FFF',
      eventTitle: {
        color: colors.white,
        fontWeight: 'normal',
        paddingLeft: 4,
        paddingVertical: 1,
      },
    }}
  />

https://user-images.githubusercontent.com/49557103/224219098-a032de8b-1536-4449-a7a0-d77fa9bf558c.mp4

**Comment by howljs** [comment]
I checked on my emulator, It works normally :'(

**Comment by Jack-Alfie** [comment]
ok. Can you try that in device. It's happen to me in all my android devices or is there anything wrong in my code?

**Comment by Jack-Alfie** [comment]
May I have any update on this please?
