### ISSUE TITLE
goToDate  future  - Add time with the date

### ISSUE THREAD

**Issue by Jack-Alfie** [howljs/react-native-calendar-kit#51]
Can you please add the time to this I need to scroll the diary to the the particular event time I have edit.

**Comment by howljs** [comment]
You can try with isoString

**Comment by howljs** [comment]
Example:
01/01/2023 12:00:00
```
calendarRef.current?.goToDate({
            date: new Date(
              new Date('2023-01-01').setHours(12, 0, 0, 0)
            ).toISOString(),
            hourScroll: true,
          });
```

**Comment by Jack-Alfie** [comment]
Thanks it fix the issue but there is another issue in version 1.13 after update when I load the events it takes time to load and the diary looks like a white screen for a few second and then it show the wrong week days on the top and it loads the correct date. Kindly find the video for that.  If you want I will open the new issue for this  

https://user-images.githubusercontent.com/49557103/224664876-6bcd5aea-8039-4604-b790-677b44345c56.mp4
