### ISSUE TITLE
Need Recurrence Rule Based Events

### ISSUE THREAD

**Issue by arun-saleth** [howljs/react-native-calendar-kit#58]
![Capture](https://user-images.githubusercontent.com/67191266/224988693-52c4cd0d-94f1-4515-8312-0ee87e1dab8f.PNG)

**Comment by howljs** [comment]
You can try this

https://github.com/howljs/react-native-calendar-kit/issues/23#issuecomment-1364473760

**Comment by arun-saleth** [comment]
Thank you. I will try this one.
