### ISSUE TITLE
Date and Day repeats in the April Month of the 2023 

### ISSUE THREAD

**Issue by kaushal-technostacks** [howljs/react-native-calendar-kit#61]
In April 2023 for the New Zealand time zone, I'm observing that Date 2 April and Sunday are rendered twice in a row, because of which the whole UI is getting disturbed Can anyone please help me out with this asap?

Please find the attachment here

Timezone is set to Wellington, New Zealand
![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-03-23 at 20 23 35](https://user-images.githubusercontent.com/107094192/227134811-68bbf2a7-f903-4b22-a631-41e33bd8c357.png)

My local timezone 

![Simulator Screen Shot - iPad Pro (12 9-inch) (6th generation) - 2023-03-23 at 12 57 38](https://user-images.githubusercontent.com/107094192/227134931-f61a8f05-1516-4126-8038-949f685408ac.png)

I have tried switching multiple time zone i.e. NewYork USA and Perth Australia and my local time zone ie. India but my not facing such issues there I guess this issue is occurring in some timezone that needs to be checked.

**Comment by kaushal-technostacks** [comment]
Hello @howljs can you please help me with this as I'm still facing this issue also, let me know if you want any details form my side thanks.

**Comment by howljs** [comment]
@kaushal-technostacks I am reviewing and fixing some other issues before releasing the new update

**Comment by howljs** [comment]
@kaushal-technostacks I published a new version. Thanks for you report
