### ISSUE TITLE
Format Hour as AM/PM

### ISSUE THREAD

**Issue by derickdecesare** [howljs/react-native-calendar-kit#62]
When I change the hourFormat to this:

hourFormat="HH:mm A"

It results in the time going from 11:00AM, 12:00PM, 13:00PM, 14:00PM and so on. 

Is there a way to fully integrate AM/PM format?

![7111](https://user-images.githubusercontent.com/105116994/228701053-42223d7d-fd26-417b-ace3-878c8671b395.jpg)

**Comment by howljs** [comment]
Correct format is "hh:mm A"

**Comment by derickdecesare** [comment]
Thank you!
