### ISSUE TITLE
Export only week header calendar

### ISSUE THREAD

**Issue by LucasReinaldo** [howljs/react-native-calendar-kit#64]
Hey folks! Great job on getting this done using the latest libs available out there. 

I was wondering if you guys plan to export only the header as a component allowing to have the same functionality of changing weeks, selecting days, animation but with custom children or even the header as it is with the functionalities mentioned before. 

That would be great!

thanks!

**Comment by howljs** [comment]
Version v2.0.0 now allows for greater customization
