### ISSUE TITLE
All day Event Like google calendar

### ISSUE THREAD

**Issue by arun-saleth** [howljs/react-native-calendar-kit#67]
Hi @howljs 

Please add this all day event feature in this package.

![thread-19637330-1329380847847769266](https://user-images.githubusercontent.com/67191266/232923739-d237657e-88ff-4975-af75-ed0b3a831a79.png)

**Comment by pencilcheck** [comment]
For now, I wonder if it supports rendering event title per day?? right now you have to scroll to the beginning of a multi-day events to see its title.

**Comment by jhuzuhua** [comment]
Any work around on this?

**Comment by raghavendran14** [comment]
Hi Guys,
Any update on this?

**Comment by howljs** [comment]
Supported in v2.0.0
