### ISSUE TITLE
Switching work week to day view Not getting current day (CRITICAL BUG)

### ISSUE THREAD

**Issue by arun-saleth** [howljs/react-native-calendar-kit#68]
@howljs 

Same as week view to day view also not working.very critical issue

version : 1.13.2

**Comment by arun-saleth** [comment]
@howljs 

I think it works based on first day of week.

For current week it should be show current day.other weeks first day of week day

**Comment by KavithaMadhu31** [comment]
same here

**Comment by howljs** [comment]
Fixed in v2.0.0
