### ISSUE TITLE
[FEATURE] Events overlap method

### ISSUE THREAD

**Issue by MinhOmega** [howljs/react-native-calendar-kit#69]
Hi author,
I think we should implement a new feature meaning: overlap instead current behavior (I can call it a lane event) You can see that via the image below:
![CleanShot 2023-04-26 at 00 48 54](https://user-images.githubusercontent.com/49482201/234360563-f25f6a2e-0b29-4c06-8ee0-2bed4384fd82.png)
Link refer: https://hoangnm.github.io/react-native-week-view/guides/overlap

Many thank

**Comment by MinhOmega** [comment]
I have updated the core function but it temporary solution for method `ignore`
![CleanShot 2023-04-26 at 01 17 39](https://user-images.githubusercontent.com/49482201/234366589-c4505a17-cc90-4660-932e-e632f6530b7c.png)

**Comment by MinhOmega** [comment]
[UPDATE]
1: normal behavior with `lane`
2: behavior `ignore`
3: behavior `stack`
Currently I have update new behavior with `stack` same keyStack
![CleanShot 2023-04-26 at 01 53 10](https://user-images.githubusercontent.com/49482201/234375345-ee16b53e-2f8a-49c8-bf7d-460d4fa72970.png)

**Comment by howljs** [comment]
Updated in v2.0.2
