### ISSUE TITLE
Per-week unavailability support

### ISSUE THREAD

**Issue by bartvanandel** [howljs/react-native-calendar-kit#7]
Hi,

Thanks for making this great library available! We're actively migrating to it in our new app. There is one missing feature though that we'd need to make full use of it.

We require being able to set availability on a day-by-day basis. In other words, we don't have repeated availability by default, so we cannot use the current unavailability, which assumes it's the same info for each week. _Note that we actually use availability, which we then convert to unavailable hours using [`xspans`](https://www.npmjs.com/package/xspans), which is totally fine. No need to change that._

It would therefore be great if the "unavailable hours" could support dates as an index as opposed to just day numbers. Would this be something that you'd like to add? I'm a bit short on time, otherwise I'd look into it myself.

**Comment by howljs** [comment]
Can you give me some pictures, videos, or any apps that have this feature?

**Comment by howljs** [comment]
Is this the feature you want? 
![Screenshot 2022-12-01 at 20 23 26](https://user-images.githubusercontent.com/33460888/205063971-7d282c92-e662-4080-a27c-0f2c0a151787.png)

**Comment by bartvanandel** [comment]
That's exactly what we need indeed!

I'm not aware of other apps that have this feature, but to be honest I haven't actively looked for it. I noticed the `unavailableHours` feature and thought we may as well use that. Great if you can make this a unique selling point of this library!

**Comment by howljs** [comment]
Ok. I think it's not too hard to do. I'll add this feature when I wake up ☺️

**Comment by SwikarBhattarai** [comment]
@howljs Hello, how to set unavailable time for hours and minutes like 9.30am to 4.30pm ?

**Comment by bartvanandel** [comment]
> @howljs Hello, how to set unavailable time for hours and minutes like 9.30am to 4.30pm ?

You can use a decimal number for the start and end values, e.g. for your example it would be

```js
{
  start: 9.5,
  end: 16.5
}
```

**Comment by howljs** [comment]
@bartvanandel  You can update to v1.8.0 
https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.8.0
![Screenshot 2022-12-02 at 08 18 57](https://user-images.githubusercontent.com/33460888/205193151-21a91cb1-c7c9-47a4-ba25-442c7805807a.png)
