### ISSUE TITLE
No support for 12-hour format

### ISSUE THREAD

**Issue by jhuzuhua** [howljs/react-native-calendar-kit#70]
Thanks for the great package. Would like to have an option to set whether the timeline will have a 12 or 24-hour format.

**Comment by arun-saleth** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/67191266/234807450-4db274e1-b7e8-445d-9fea-936963636d5f.png)
![Screenshot_3](https://user-images.githubusercontent.com/67191266/234807708-5f3762bd-e296-4109-bbed-a21de1233157.png)

i think you mentioned above 

24 Hour Format: 
hourFormat="H:mm"

12 Hour Format:
hourFormat="hh:mm A"

**Comment by jhuzuhua** [comment]
> ![Screenshot_2](https://user-images.githubusercontent.com/67191266/234807450-4db274e1-b7e8-445d-9fea-936963636d5f.png) ![Screenshot_3](https://user-images.githubusercontent.com/67191266/234807708-5f3762bd-e296-4109-bbed-a21de1233157.png)
> 
> i think you mentioned above
> 
> 24 Hour Format: hourFormat="H:mm"
> 
> 12 Hour Format: hourFormat="hh:mm A"

Hi @arun-saleth I just saw a while ago the hourFormat prop. My bad. But many thanks for answering my inquiry!
