### ISSUE TITLE
onpressbackground not get current time when set start and end prop

### ISSUE THREAD

**Issue by arun-saleth** [howljs/react-native-calendar-kit#71]
when set start=7 end end=5 hour ,on while clicking 7-8 between it returns 12:00.the issue will happens all other hours also

@howljs can you check and fix this?

**Comment by joaomellogomes** [comment]
It happens to me as well. I'd really like to have this working with time range.

**Comment by joaomellogomes** [comment]
It happens to me as well. I'd really like to have this working with time range.

But a temporary workaround to me was add the value of startHour to the date that comes from onPressBackground event, like this:

`
const onPressBackground = (date: string) => {
    const start = dayjs(date).add(startHour, 'hours').toISOString()
    const end = dayjs(start).add(1, 'h')

    const newEvent: EventItem = {
      start,
      end: end.toISOString(),
      id: '1',
      title: 'Event',
      color: colors.purple500
    }
    setEvent(newEvent)
  }
`

**Comment by basaksilasanli** [comment]
Hi @howljs How can I get `start time` and `end time` using the `onPressBackground` function? At the moment, I can get dateTime like this;

 `{"dateTime": "2024-12-09T20:55:00.000Z"}`

**Comment by howljs** [comment]
> Hi @howljs How can I get `start time` and `end time` using the `onPressBackground` function? At the moment, I can get only `dateTime` like this;
> 
> `{"dateTime": "2024-12-09T20:55:00.000Z"}`

You can calculate based on your duration
