### ISSUE TITLE
`timeZoneData` incomplete

### ISSUE THREAD

**Issue by callaars** [howljs/react-native-calendar-kit#73]
There are loads of timezones missing from your `timeZoneData` data set. Where did you get this information, perhaps I can adjust them to contain all timezones.

**Comment by howljs** [comment]
I have switched to using `Luxon` to handle timezone.

Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the [example](https://github.com/howljs/react-native-calendar-kit) code if you want to use the library early.
