### ISSUE TITLE
[Feature request]  Google calendar like drag to create

### ISSUE THREAD

**Issue by swangy** [howljs/react-native-calendar-kit#77]
Trying to work through gesture handler to imitate google calendar's drag to create feature, where the length of the event is changed during the long press.

where do you start??!

https://github.com/howljs/react-native-calendar-kit/assets/752891/bc9ebbe7-67d1-4988-8d4a-77d52a01a061

**Comment by swangy** [comment]
Ok, @howljs took a first stab at it.. made a PR here
https://github.com/howljs/react-native-calendar-kit/pull/80

**Comment by howljs** [comment]
Supported since version 2.0.0
