### ISSUE TITLE
How to disable event overlap in drag or resize event ?

### ISSUE THREAD

**Issue by devaniumesh** [howljs/react-native-calendar-kit#81]
Hi,

When i have multiple events, it will overlap events another event in same time slot. **I want only one event per time slot behaviour,** 
what is the parameter to set that behaviour ? can you please specify that.
![Screenshot_1691848197](https://github.com/howljs/react-native-calendar-kit/assets/10271644/b09462c7-a547-45ee-8b27-ba37d08dfecf)

**Comment by howljs** [comment]
Updated in v2.0.2
