### ISSUE TITLE
How to add multiple resources on day ?

### ISSUE THREAD

**Issue by devaniumesh** [howljs/react-native-calendar-kit#82]
Hi,

Can you also figure out one urgent fix ? In current calendar function, we aren't able to add resources with that day. Can you please add extra param, so we can also add multiple resource to same day, and all have different events attached. As you can see below screenshot

![image](https://github.com/howljs/react-native-calendar-kit/assets/10271644/971dbd6e-c283-40cd-970c-87c6a9f78d07)

**Comment by qrozrafa** [comment]
how to all-day ?
