### ISSUE TITLE
`TimelineCalendar` is not reacting for a first touch

### ISSUE THREAD

**Issue by k4wo** [howljs/react-native-calendar-kit#87]
`TimelineCalendar` is not reacting for a first touch. Vertical/horizontal scroll doesn't work. It happens only on ios device (in simulator and android device everything is ok).

I run app on the phone and everything works as expected, then app goes to background and I bring it to foreground. In this moment app is not responsive doesn't react on first touch. I need touch it and then can scroll it.

I've tried on two devices and result is the same. [This function](https://github.com/howljs/react-native-calendar-kit/blob/03491e84bea8a213f3f2b0565995381342f60600/src/components/Timeline/TimelineSlots.tsx#L185) is not invoked. I don't know if it is related to my RN configuration.

`"@howljs/calendar-kit": "^1.13.2"`
`RN:  v0.76.7`

I've simplified my app to this code and it still doesn't work.
```js
import React, {useEffect} from 'react';
import BootSplash from 'react-native-bootsplash';

import {TimelineCalendar} from '@howljs/calendar-kit';

const App = () => {
  useEffect(() => {
    BootSplash.hide({fade: true});
  }, []);

  return <TimelineCalendar />;
};

export default App;
```

**Comment by k4wo** [comment]
I found something. The issue is caused by [GestureDetector](https://github.com/howljs/react-native-calendar-kit/blob/main/src/components/Timeline/index.tsx#L299).

**Comment by parthkanani93** [comment]
Have you solved that @k4wo ??

**Comment by parthkanani93** [comment]
Fixed using below changess

`diff --git a/node_modules/@howljs/calendar-kit/src/components/Timeline/index.tsx b/node_modules/@howljs/calendar-kit/src/components/Timeline/index.tsx
index 23f2b14..6080250 100644
--- a/node_modules/@howljs/calendar-kit/src/components/Timeline/index.tsx
+++ b/node_modules/@howljs/calendar-kit/src/components/Timeline/index.tsx
@@ -296,7 +296,7 @@ const Timeline: React.ForwardRefRenderFunction<
         />
       )}
       <View style={styles.content} onLayout={_onContentLayout}>
-        <GestureDetector gesture={Gesture.Race(dragCreateGesture, zoomGesture)}>
+        {/* <GestureDetector gesture={Gesture.Race(dragCreateGesture, zoomGesture)}> */}
           <TimelineSlots
             {...other}
             events={groupedEvents}
@@ -305,7 +305,7 @@ const Timeline: React.ForwardRefRenderFunction<
             isLoading={isLoading}
             onLongPressBackground={_onLongPressBackground}
           />
-        </GestureDetector>
+        {/* </GestureDetector> */}
         {isDraggingCreate && (
           <DragCreateItem
             offsetX={dragXPosition}`

**Comment by parthkanani93** [comment]
Fixed By using this patch
[@howljs+calendar-kit+1.13.2.patch](https://github.com/user-attachments/files/16159434/%40howljs%2Bcalendar-kit%2B1.13.2.patch)

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the [example](https://github.com/howljs/react-native-calendar-kit) code if you want to use the library early.
