### ISSUE TITLE
Works unstable on iPhone

### ISSUE THREAD

**Issue by Haianh9999** [howljs/react-native-calendar-kit#90]
Package.json 
<img width="571" alt="Screenshot 2023-12-26 at 01 35 29" src="https://github.com/howljs/react-native-calendar-kit/assets/96808297/9e6dd908-4d36-4a8f-bdd9-dc88aa5dd619">
Video: https://drive.google.com/file/d/1eYu5vOftRx6kYZ0uGtDunEMCHk6NDXS2/view?usp=sharing

**Comment by Haianh9999** [comment]
@howljs please check here 🙇

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the example code if you want to use the library early.
