### ISSUE TITLE
Any way to pin events to a lane?

### ISSUE THREAD

**Issue by jagthedrummer** [howljs/react-native-calendar-kit#92]
I'm working on displaying a schedule for a music festival where there will be several stages operating at once on the same day. I'd like to find a way to ensure that all of the events for a particular stage show up in the same column/lane in the timeline regardless of the start time of events.

Here's an example:

![CleanShot 2024-01-04 at 15 18 38](https://github.com/howljs/react-native-calendar-kit/assets/58702/5636a3e1-8bd1-4e5f-96a7-25cc4f96d092)

I'm looking for a way to get those last two events to switch columns, so that Stage 1 events are all in the first column, and Stage 2 events are all in the second column.

Do you have any tips on how I might be able to make that happen?

**Comment by howljs** [comment]
Updated in v2.0.5

**Comment by jagthedrummer** [comment]
Hey, I'm late to the party, but I've just checked out the "resources calendar" mode, and it's awesome! Exactly the kind of thing I was hoping for. Thank you!
