### ISSUE TITLE
onPressEvent does not emit an EventItem

### ISSUE THREAD

**Issue by phillihoch** [howljs/react-native-calendar-kit#93]
I found out, that the onPressEvent event does not has an EventItem inside its props.

This is the structure from the calendar-kit:
```
export interface EventItem {
  /** Unique ID for the event. */
  id: string;
  /** Start date of the event. (ISOString) */
  start: string;
  /** End date of the event. (ISOString) */
  end: string;
  /** Title of the event */
  title?: string;
  /** Background color of the event */
  color?: string;
  /** Container style of the event */
  containerStyle?: StyleProp<ViewStyle>;
  [key: string]: any;
}
```

This is the structure it actually emits:
```
export interface EventItem {
  /** Unique ID for the event. */
  id: string;
  /** Start date of the event. (Date) */
  start: Date;
  /** End date of the event. (Date) */
  end: Date;
  /** Title of the event */
  title?: string;
  /** Background color of the event */
  color?: string;
  /** Container style of the event */
  containerStyle?: StyleProp<ViewStyle>;
  [key: string]: any;
}
```
It is a JavaScript Date object and not a string.

I found out because i want to pass an event through a navigator and it said it has unserializable props (start and end).

Here's proof:
I can execute Date Object functions of the prop of the onPressEvent handler:
<img width="304" alt="image" src="https://github.com/howljs/react-native-calendar-kit/assets/64873861/c4d83040-50e6-426e-aa42-9cd5afb0555b">
TypeScript states an error but the code is working fine, because the start property is a Date object.

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the [example](https://github.com/howljs/react-native-calendar-kit) code if you want to use the library early.
