### ISSUE TITLE
Can't build due to dependency

### ISSUE THREAD

**Issue by albertpco** [howljs/react-native-calendar-kit#95]
Any shot anyone has a way to work around the reanimated 3+ migration? Currently blocking a big launch and I love what @howljs has done with this kit. If not I'll try and see if I can redo some of the animations deeply, trying to get EAS build to fire

**Comment by kota113** [comment]
Is this related to #83?

**Comment by albertpco** [comment]
Yep but when I did you change (tried it myself prior just to install some npm packages and all), for some reason my day/3 day views are both blank. 5 Day and 7 day view both work perfectly though...?

**Comment by kota113** [comment]
Oh I haven't tried the 3day view.

**Comment by howljs** [comment]
Fixed in v2.0.0
