### ISSUE TITLE
 TypeError: Cannot assign to read-only property 'validated'

### ISSUE THREAD

**Issue by yashBrahma** [howljs/react-native-calendar-kit#99]
Giving an error when I try to swipe to the left 4times and 3times to the right both android and ios
 
 ![image](https://github.com/howljs/react-native-calendar-kit/assets/109267775/531acd4c-8f8b-4089-bb11-54d0ef7e0beb)

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the [example](https://github.com/howljs/react-native-calendar-kit) code if you want to use the library early.
